[[runners]]
  name = "alpine"
  limit = 0
  executor = "docker"
  shell = "sh"
  privileged = false
  environment = ["LC_ALL=en_US.UTF-8"]
  disable_verbose = false
  wait_for_services_timeout = 30
  volumes = ["/etc/hosts:/etc/hosts:z"]
